[query]
prompt_style.fg = "Red"

[start]
command = '''rg --column --line-number --no-heading --color=always --smart-case "$FZF_QUERY"'''
ansi = true

[columns]
max = 3
split = '^(.*?):(\d+:\d+):(.*)$'
default = 3

[results]

[[preview.layout]]
command = '''
line={2}
if command -v bat >/dev/null 2>&1; then
    bat --color=always --highlight-line ${line%%:*} {1}
else
    cat {1}
fi
'''
border = { type = "LightDoubleDashed", color = "DarkGray" }
side = "top"
percentage = 50

[preview]
show = true
scroll.percentage = 70
scroll.index = 2

[binds]
"Start" = "@enter_rg"
"@enter_rg" = [ # Reload on query change, disable reparsing, update bind
"Filtering(false)",
'''Bind(QueryChange = Reload)''',
# Prompt indicator (
'''Transform(
    if [[ -n "$MM_QUERY" ]]; then
        echo "SetStyledPrompt({blue,italic:(${MM_QUERY#\%1 } )} )"
    else
        echo "SetPrompt(rg> )"
    fi

    echo "SetQuery($MM_STORE)"
    echo "Store($MM_QUERY)"
)''',
"Bind(@reload = @enter_mm)",
]
"@enter_mm" = [
"Filtering(true)",
"Unbind(QueryChange)",
'''Transform(
    if [[ -n "$MM_QUERY" ]]; then
        echo "SetPrompt(($MM_QUERY) )"
    else
        echo "SetStyledPrompt({blue,italic:mm> })"
    fi

    echo "SetQuery($MM_STORE)"
    echo "Store($MM_QUERY)"
    echo "SwitchColumn(1)"
)
''',
"Bind(@reload = @enter_rg)"
]

"ctrl-r" = "@reload"

# Navigation
"ctrl-." = "NextColumn"
"enter" = "Become($EDITOR {1})"
"?" = "SwitchPreview"
